# Generated by Django 3.2.8 on 2021-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=50)),
                ('f_description', models.TextField()),
                ('f_image', models.ImageField(upload_to='feature/')),
            ],
        ),
    ]
